# Site
repository: heavymedl/resume
favicon: images/favicon.ico

# Personal info
name: Kurt Medley
title: Senior Software Engineer
email: kurtdmedley@gmail.com
website: www.github.com/heavymedl

# Social links
# twitter_username: facespics
github_username:  heavymedl
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: heavy.medl
linkedin_username: kurt-medley
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

additional_links:
  - title: npm link
    icon: fa-npm
    url: https://www.npmjs.com/~heavymedl

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a software engineer based in the greater Seattle area. I've been doing full-stack development on enterprise applications for the better part of a decade. I write tons of <mark>JavaScript</mark>, <mark>Python</mark>, and <mark>Java</mark>. 
  
  I currently work as a front-end engineer for REI's Experiences division writing <mark>Vue.js</mark> components amongst other things.

  For a comprehensive list of skills and general proficiencies, please see the bottom section.
#Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

# I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Skills and proficiencies:
  - Languages: JavaScript, Java, Haskell, Python, Bash, HTML, SCSS/LESS/CSS, JSON/XML, SQL
  - Technologies, libraries, etc: Webpack, Vue.js, React/Redux (some), Node.js, Express.js, Lodash, GIT, Bootstrap, AWS EC2/S3, jQuery, WebSphere Commerce, Windows/OSX/Ubuntu

  ---

  Outside of work I love:
  - Regular human activities including hiking, snowboarding, and camping with my wife, playing with our mini Goldendoodle, Freya, and football.
  - Exploring new programming languages, technologies, platforms, and frameworks. 
  - 3D printing. I enjoy tinkering with mods and upgrades for my printers, and of course, printing itself. I own an Ender 5 and an Original Prusa i3 MK3S
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

darkmode: never
